# KerberosSDR Python GUI

# Copyright (C) 2018-2019  Carl Laufer, Tamás Pető
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_hydra_dev.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtCore import QLocale

QLocale.setDefault(QLocale(QLocale.C))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("KerberosSDR")
        MainWindow.resize(1366, 870)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget_config = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget_config.setMaximumSize(QtCore.QSize(290, 16777215))
        self.stackedWidget_config.setObjectName("stackedWidget_config")
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtGui.QGroupBox(self.page_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.doubleSpinBox_center_freq = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_center_freq.setDecimals(4)
        self.doubleSpinBox_center_freq.setMinimum(25.0)
        self.doubleSpinBox_center_freq.setMaximum(2000.0)
        self.doubleSpinBox_center_freq.setProperty("value", 100.0)
        self.doubleSpinBox_center_freq.setObjectName("doubleSpinBox_center_freq")
        self.gridLayout_16.addWidget(self.doubleSpinBox_center_freq, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 0, 0, 1, 1)

        # Sampling Freq
        self.doubleSpinBox_sampling_freq = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_sampling_freq.setMinimum(1.0)
        self.doubleSpinBox_sampling_freq.setMaximum(3.2)
        self.doubleSpinBox_sampling_freq.setObjectName("doubleSpinBox_sampling_freq")
        self.gridLayout_16.addWidget(self.doubleSpinBox_sampling_freq, 1, 1, 1, 1)

        # self.comboBox_sampling_freq = QtGui.QComboBox(self.groupBox_7)
        # self.comboBox_sampling_freq.setObjectName("comboBox_sampling_freq")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.comboBox_sampling_freq.addItem("")
        # self.gridLayout_16.addWidget(self.comboBox_sampling_freq, 1, 1, 1, 1)

        self.checkBox_en_uniform_gain = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_en_uniform_gain.setObjectName("checkBox_en_uniform_gain")
        self.gridLayout_16.addWidget(self.checkBox_en_uniform_gain, 2, 0, 1, 1)

        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_16.addWidget(self.label_18, 3, 0, 1, 1)

        self.label_gain_2 = QtGui.QLabel(self.groupBox_7)
        self.label_gain_2.setObjectName("label_gain_2")
        self.gridLayout_16.addWidget(self.label_gain_2, 4, 0, 1, 1)

        self.label_gain_3 = QtGui.QLabel(self.groupBox_7)
        self.label_gain_3.setObjectName("label_gain_3")
        self.gridLayout_16.addWidget(self.label_gain_3, 5, 0, 1, 1)

        self.label_gain_4 = QtGui.QLabel(self.groupBox_7)
        self.label_gain_4.setObjectName("label_gain_4")
        self.gridLayout_16.addWidget(self.label_gain_4, 6, 0, 1, 1)

        self.comboBox_gain = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_gain.setObjectName("comboBox_gain")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain, 3, 1, 1, 1)

        self.comboBox_gain_2 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_gain_2.setObjectName("comboBox_gain_2")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.comboBox_gain_2.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain_2, 4, 1, 1, 1)

        self.comboBox_gain_3 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_gain_3.setObjectName("comboBox_gain_3")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.comboBox_gain_3.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain_3, 5, 1, 1, 1)

        self.comboBox_gain_4 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_gain_4.setObjectName("comboBox_gain_4")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain_4, 6, 1, 1, 1)

        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.pushButton_set_receiver_config = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_set_receiver_config.setObjectName(
            "pushButton_set_receiver_config"
        )
        self.gridLayout_17.addWidget(self.pushButton_set_receiver_config, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_8)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.checkBox_en_dc_compensation = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_en_dc_compensation.setText("")
        self.checkBox_en_dc_compensation.setObjectName("checkBox_en_dc_compensation")
        self.gridLayout_2.addWidget(self.checkBox_en_dc_compensation, 0, 1, 1, 1)
        self.doubleSpinBox_filterbw = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_filterbw.setMaximum(3400.0)
        self.doubleSpinBox_filterbw.setProperty("value", 150.0)
        self.doubleSpinBox_filterbw.setObjectName("doubleSpinBox_filterbw")
        self.gridLayout_2.addWidget(self.doubleSpinBox_filterbw, 1, 1, 1, 1)
        self.spinBox_fir_tap_size = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_fir_tap_size.setMaximum(10000)
        self.spinBox_fir_tap_size.setObjectName("spinBox_fir_tap_size")
        self.gridLayout_2.addWidget(self.spinBox_fir_tap_size, 2, 1, 1, 1)
        self.spinBox_decimation = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_decimation.setMinimum(1)
        self.spinBox_decimation.setMaximum(1000)
        self.spinBox_decimation.setObjectName("spinBox_decimation")
        self.gridLayout_2.addWidget(self.spinBox_decimation, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.checkBox_en_spectrum = QtGui.QCheckBox(self.page_4)
        self.checkBox_en_spectrum.setObjectName("checkBox_en_spectrum")
        self.verticalLayout_7.addWidget(self.checkBox_en_spectrum)
        self.stackedWidget_config.addWidget(self.page_4)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)

        self.checkBox_en_sync_display = QtGui.QCheckBox(self.groupBox)
        self.checkBox_en_sync_display.setText("")
        self.checkBox_en_sync_display.setObjectName("checkBox_en_sync_display")
        self.gridLayout_8.addWidget(self.checkBox_en_sync_display, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)
        self.checkBox_en_noise_source = QtGui.QCheckBox(self.groupBox)
        self.checkBox_en_noise_source.setText("")
        self.checkBox_en_noise_source.setObjectName("checkBox_en_noise_source")
        self.gridLayout_8.addWidget(self.checkBox_en_noise_source, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.pushButton_del_sync_history = QtGui.QPushButton(self.groupBox)
        self.pushButton_del_sync_history.setObjectName("pushButton_del_sync_history")
        self.verticalLayout_2.addWidget(self.pushButton_del_sync_history)
        self.pushButton_sync = QtGui.QPushButton(self.groupBox)
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.verticalLayout_2.addWidget(self.pushButton_sync)
        self.pushButton_iq_calib = QtGui.QPushButton(self.groupBox)
        self.pushButton_iq_calib.setObjectName("pushButton_iq_calib")
        self.verticalLayout_2.addWidget(self.pushButton_iq_calib)

        # Add Resync Time Control Box
        self.label_resync_time = QtGui.QLabel(self.groupBox)
        self.label_resync_time.setObjectName("label_resync_time")
        self.gridLayout_8.addWidget(self.label_resync_time, 2, 0, 1, 1)

        self.spinBox_resync_time = QtGui.QSpinBox(self.groupBox)
        self.spinBox_resync_time.setObjectName("spinBox_resync_time")
        self.spinBox_resync_time.setMinimum(0)
        self.spinBox_resync_time.setMaximum(99999)

        self.gridLayout_8.addWidget(self.spinBox_resync_time, 2, 1, 1, 1)

        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(
            20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding
        )
        self.gridLayout_9.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.stackedWidget_config.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.comboBox_antenna_alignment = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_antenna_alignment.setObjectName("comboBox_antenna_alignment")
        self.comboBox_antenna_alignment.addItem("")
        self.comboBox_antenna_alignment.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_antenna_alignment, 0, 1, 1, 1)
        self.doubleSpinBox_DOA_d = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_DOA_d.setDecimals(4)
        # self.doubleSpinBox_DOA_d.setMaximum(10.0)
        self.doubleSpinBox_DOA_d.setProperty("value", 0.5)
        self.doubleSpinBox_DOA_d.setObjectName("doubleSpinBox_DOA_d")
        self.gridLayout_4.addWidget(self.doubleSpinBox_DOA_d, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.pushButton_DOA_cal_90 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_DOA_cal_90.setObjectName("pushButton_DOA_cal_90")
        self.gridLayout_7.addWidget(self.pushButton_DOA_cal_90, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.page_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_en_DOA_MEM = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MEM.setText("")
        self.checkBox_en_DOA_MEM.setObjectName("checkBox_en_DOA_MEM")
        self.gridLayout.addWidget(self.checkBox_en_DOA_MEM, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.checkBox_en_DOA_Bartlett = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Bartlett.setText("")
        self.checkBox_en_DOA_Bartlett.setObjectName("checkBox_en_DOA_Bartlett")
        self.gridLayout.addWidget(self.checkBox_en_DOA_Bartlett, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkBox_en_DOA_Capon = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Capon.setText("")
        self.checkBox_en_DOA_Capon.setObjectName("checkBox_en_DOA_Capon")
        self.gridLayout.addWidget(self.checkBox_en_DOA_Capon, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.spinBox_DOA_sample_size = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_DOA_sample_size.setMinimum(1)
        self.spinBox_DOA_sample_size.setMaximum(22)
        self.spinBox_DOA_sample_size.setProperty("value", 15)
        self.spinBox_DOA_sample_size.setObjectName("spinBox_DOA_sample_size")
        self.gridLayout.addWidget(self.spinBox_DOA_sample_size, 7, 1, 1, 1)
        self.checkBox_en_DOA_MUSIC = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MUSIC.setText("")
        self.checkBox_en_DOA_MUSIC.setObjectName("checkBox_en_DOA_MUSIC")
        self.gridLayout.addWidget(self.checkBox_en_DOA_MUSIC, 5, 1, 1, 1)
        self.checkBox_en_DOA = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA.setText("")
        self.checkBox_en_DOA.setChecked(True)
        self.checkBox_en_DOA.setObjectName("checkBox_en_DOA")
        self.gridLayout.addWidget(self.checkBox_en_DOA, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.checkBox_en_DOA_FB_avg = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_FB_avg.setText("")
        self.checkBox_en_DOA_FB_avg.setObjectName("checkBox_en_DOA_FB_avg")
        self.gridLayout.addWidget(self.checkBox_en_DOA_FB_avg, 8, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.stackedWidget_config.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_en_passive_radar = QtGui.QCheckBox(self.page_3)
        self.checkBox_en_passive_radar.setObjectName("checkBox_en_passive_radar")
        self.verticalLayout_3.addWidget(self.checkBox_en_passive_radar)
        self.groupBox_3 = QtGui.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.spinBox_surv_ch_select = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_surv_ch_select.setMaximum(3)
        self.spinBox_surv_ch_select.setProperty("value", 1)
        self.spinBox_surv_ch_select.setObjectName("spinBox_surv_ch_select")
        self.gridLayout_11.addWidget(self.spinBox_surv_ch_select, 1, 1, 1, 1)
        self.spinBox_ref_ch_select = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_ref_ch_select.setMaximum(3)
        self.spinBox_ref_ch_select.setObjectName("spinBox_ref_ch_select")
        self.gridLayout_11.addWidget(self.spinBox_ref_ch_select, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 2, 0, 1, 1)
        self.spinBox_pr_sample_size = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_pr_sample_size.setMaximum(25)
        self.spinBox_pr_sample_size.setProperty("value", 15)
        self.spinBox_pr_sample_size.setObjectName("spinBox_pr_sample_size")
        self.gridLayout_11.addWidget(self.spinBox_pr_sample_size, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.page_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_18.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 1, 0, 1, 1)
        self.checkBox_en_td_filter = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_en_td_filter.setText("")
        self.checkBox_en_td_filter.setObjectName("checkBox_en_td_filter")
        self.gridLayout_18.addWidget(self.checkBox_en_td_filter, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_18.addWidget(self.label_26, 2, 0, 1, 1)
        self.spinBox_td_filter_dimension = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_td_filter_dimension.setMinimum(1)
        self.spinBox_td_filter_dimension.setMaximum(16384)
        self.spinBox_td_filter_dimension.setProperty("value", 127)
        self.spinBox_td_filter_dimension.setObjectName("spinBox_td_filter_dimension")
        self.gridLayout_18.addWidget(self.spinBox_td_filter_dimension, 2, 1, 1, 1)
        self.comboBox_td_filter_method = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_td_filter_method.setObjectName("comboBox_td_filter_method")
        self.comboBox_td_filter_method.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_td_filter_method, 1, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)

        # self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9 = QtGui.QGroupBox(self.page_3)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.doubleSpinBox_cc_det_max_Doppler = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBox_cc_det_max_Doppler.setMaximum(100000.0)
        self.doubleSpinBox_cc_det_max_Doppler.setProperty("value", 500.0)
        self.doubleSpinBox_cc_det_max_Doppler.setObjectName(
            "doubleSpinBox_cc_det_max_Doppler"
        )
        self.gridLayout_20.addWidget(self.doubleSpinBox_cc_det_max_Doppler, 1, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_20.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_9)
        self.label_28.setObjectName("label_28")
        self.gridLayout_20.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_9)
        self.label_29.setObjectName("label_29")
        self.gridLayout_20.addWidget(self.label_29, 2, 0, 1, 1)
        self.doubleSpinBox_cc_det_max_range = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBox_cc_det_max_range.setMaximum(100000.0)
        self.doubleSpinBox_cc_det_max_range.setProperty("value", 128.0)
        self.doubleSpinBox_cc_det_max_range.setObjectName(
            "doubleSpinBox_cc_det_max_range"
        )
        self.gridLayout_20.addWidget(self.doubleSpinBox_cc_det_max_range, 0, 1, 1, 1)
        self.comboBox_cc_det_windowing = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_cc_det_windowing.setObjectName("comboBox_cc_det_windowing")
        self.comboBox_cc_det_windowing.addItem("")
        self.comboBox_cc_det_windowing.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_cc_det_windowing, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_9)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 3, 0, 1, 1)
        self.spinBox_rd_dyn_range = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_rd_dyn_range.setMaximum(100)
        self.spinBox_rd_dyn_range.setProperty("value", 20)
        self.spinBox_rd_dyn_range.setObjectName("spinBox_rd_dyn_range")
        self.gridLayout_20.addWidget(self.spinBox_rd_dyn_range, 3, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_3.addWidget(self.groupBox_9)

        self.groupBox_10 = QtGui.QGroupBox(self.page_3)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_35 = QtGui.QLabel(self.groupBox_10)
        self.label_35.setObjectName("label_35")
        self.gridLayout_22.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_10)
        self.label_34.setObjectName("label_34")
        self.gridLayout_22.addWidget(self.label_34, 3, 0, 1, 1)
        self.checkBox_en_autodet = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_en_autodet.setText("")
        self.checkBox_en_autodet.setObjectName("checkBox_en_autodet")
        self.gridLayout_22.addWidget(self.checkBox_en_autodet, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_10)
        self.label_33.setObjectName("label_33")
        self.gridLayout_22.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_10)
        self.label_36.setObjectName("label_36")
        self.gridLayout_22.addWidget(self.label_36, 2, 0, 1, 1)
        self.spinBox_cfar_est_win = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_cfar_est_win.setMaximum(100)
        self.spinBox_cfar_est_win.setProperty("value", 10)
        self.spinBox_cfar_est_win.setObjectName("spinBox_cfar_est_win")
        self.gridLayout_22.addWidget(self.spinBox_cfar_est_win, 1, 1, 1, 1)
        self.spinBox_cfar_guard_win = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_cfar_guard_win.setProperty("value", 4)
        self.spinBox_cfar_guard_win.setObjectName("spinBox_cfar_guard_win")
        self.gridLayout_22.addWidget(self.spinBox_cfar_guard_win, 2, 1, 1, 1)
        self.doubleSpinBox_cfar_threshold = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_cfar_threshold.setProperty("value", 13.0)
        self.doubleSpinBox_cfar_threshold.setObjectName("doubleSpinBox_cfar_threshold")
        self.gridLayout_22.addWidget(self.doubleSpinBox_cfar_threshold, 3, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_10)

        # Peak hold groupbox
        self.groupBox_11 = QtGui.QGroupBox(self.page_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_25 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_37 = QtGui.QLabel(self.groupBox_11)
        self.label_37.setObjectName("label_37")
        self.gridLayout_25.addWidget(self.label_37, 0, 0, 1, 1)
        self.checkBox_en_peakhold = QtGui.QCheckBox(self.groupBox_11)
        self.checkBox_en_peakhold.setText("")
        self.checkBox_en_peakhold.setObjectName("checkBox_en_peakhold")
        self.gridLayout_25.addWidget(self.checkBox_en_peakhold, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_11)

        self.stackedWidget_config.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.stackedWidget_config)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_power_level = QtGui.QLabel(self.groupBox_6)
        self.label_power_level.setObjectName("label_power_level")
        self.gridLayout_14.addWidget(self.label_power_level, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_update_rate = QtGui.QLabel(self.groupBox_6)
        self.label_update_rate.setObjectName("label_update_rate")
        self.gridLayout_14.addWidget(self.label_update_rate, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)

        self.gridLayout_15.addLayout(self.gridLayout_14, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(
            20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding
        )

        self.gridLayout_15.addItem(spacerItem1, 6, 0, 1, 1)

        self.pushButton_close = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_15.addWidget(self.pushButton_close, 5, 0, 1, 1)

        self.pushButton_proc_control = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_proc_control.setObjectName("pushButton_proc_control")
        self.gridLayout_15.addWidget(self.pushButton_proc_control, 4, 0, 1, 1)

        self.pushButton_dumping_data = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_dumping_data.setObjectName("pushButton_dumping_data")
        self.gridLayout_15.addWidget(self.pushButton_dumping_data, 5, 0, 1, 1)

        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_spectrum = QtGui.QWidget()
        self.tab_spectrum.setObjectName("tab_spectrum")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_spectrum)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_spectrum = QtGui.QGridLayout()
        self.gridLayout_spectrum.setObjectName("gridLayout_spectrum")
        self.gridLayout_6.addLayout(self.gridLayout_spectrum, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_spectrum, "")
        self.tab_symc = QtGui.QWidget()
        self.tab_symc.setObjectName("tab_symc")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_symc)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_sync = QtGui.QGridLayout()
        self.gridLayout_sync.setObjectName("gridLayout_sync")
        self.gridLayout_5.addLayout(self.gridLayout_sync, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_symc, "")
        self.tab_DOA = QtGui.QWidget()
        self.tab_DOA.setObjectName("tab_DOA")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_DOA)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_DOA = QtGui.QGridLayout()
        self.gridLayout_DOA.setObjectName("gridLayout_DOA")
        self.gridLayout_12.addLayout(self.gridLayout_DOA, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DOA, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_23 = QtGui.QGridLayout(self.tab)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_RD = QtGui.QGridLayout()
        self.gridLayout_RD.setObjectName("gridLayout_RD")
        self.gridLayout_23.addLayout(self.gridLayout_RD, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_config.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("KerberosSDR")
        self.groupBox_7.setTitle("Receiver configaration")
        self.label_4.setText("Sampling frequency [MHz]:")
        # self.comboBox_sampling_freq.setItemText(0, "0.25")
        # self.comboBox_sampling_freq.setItemText(1, "0.900001")
        # self.comboBox_sampling_freq.setItemText(2, "1.024")
        # self.comboBox_sampling_freq.setItemText(3, "1.4")
        # self.comboBox_sampling_freq.setItemText(4, "1.8")
        # self.comboBox_sampling_freq.setItemText(5, "1.92")
        # self.comboBox_sampling_freq.setItemText(6, "2.0")
        # self.comboBox_sampling_freq.setItemText(7, "2.4")
        # self.comboBox_sampling_freq.setItemText(8, "2.56")
        # self.comboBox_sampling_freq.setCurrentIndex(2)

        self.checkBox_en_uniform_gain.setText("Uniform Gain")

        self.label_3.setText("Center frequency [MHz]:")
        self.label_18.setText("RX1 Gain [dB]:")
        self.comboBox_gain.setItemText(0, "0")
        self.comboBox_gain.setItemText(1, "0.9")
        self.comboBox_gain.setItemText(2, "1.4")
        self.comboBox_gain.setItemText(3, "2.7")
        self.comboBox_gain.setItemText(4, "3.7")
        self.comboBox_gain.setItemText(5, "7.7")
        self.comboBox_gain.setItemText(6, "8.7")
        self.comboBox_gain.setItemText(7, "12.5")
        self.comboBox_gain.setItemText(8, "14.4")
        self.comboBox_gain.setItemText(9, "15.7")
        self.comboBox_gain.setItemText(10, "16.6")
        self.comboBox_gain.setItemText(11, "19.7")
        self.comboBox_gain.setItemText(12, "20.7")
        self.comboBox_gain.setItemText(13, "22.9")
        self.comboBox_gain.setItemText(14, "25.4")
        self.comboBox_gain.setItemText(15, "28.0")
        self.comboBox_gain.setItemText(16, "29.7")
        self.comboBox_gain.setItemText(17, "32.8")
        self.comboBox_gain.setItemText(18, "33.8")
        self.comboBox_gain.setItemText(19, "36.4")
        self.comboBox_gain.setItemText(20, "37.2")
        self.comboBox_gain.setItemText(21, "38.6")
        self.comboBox_gain.setItemText(22, "40.2")
        self.comboBox_gain.setItemText(23, "42.1")
        self.comboBox_gain.setItemText(24, "43.4")
        self.comboBox_gain.setItemText(25, "43.9")
        self.comboBox_gain.setItemText(26, "44.5")
        self.comboBox_gain.setItemText(27, "48.0")
        self.comboBox_gain.setItemText(28, "49.6")

        self.label_gain_2.setText("RX2 Gain [dB]:")
        self.comboBox_gain_2.setItemText(0, "0")
        self.comboBox_gain_2.setItemText(1, "0.9")
        self.comboBox_gain_2.setItemText(2, "1.4")
        self.comboBox_gain_2.setItemText(3, "2.7")
        self.comboBox_gain_2.setItemText(4, "3.7")
        self.comboBox_gain_2.setItemText(5, "7.7")
        self.comboBox_gain_2.setItemText(6, "8.7")
        self.comboBox_gain_2.setItemText(7, "12.5")
        self.comboBox_gain_2.setItemText(8, "14.4")
        self.comboBox_gain_2.setItemText(9, "15.7")
        self.comboBox_gain_2.setItemText(10, "16.6")
        self.comboBox_gain_2.setItemText(11, "19.7")
        self.comboBox_gain_2.setItemText(12, "20.7")
        self.comboBox_gain_2.setItemText(13, "22.9")
        self.comboBox_gain_2.setItemText(14, "25.4")
        self.comboBox_gain_2.setItemText(15, "28.0")
        self.comboBox_gain_2.setItemText(16, "29.7")
        self.comboBox_gain_2.setItemText(17, "32.8")
        self.comboBox_gain_2.setItemText(18, "33.8")
        self.comboBox_gain_2.setItemText(19, "36.4")
        self.comboBox_gain_2.setItemText(20, "37.2")
        self.comboBox_gain_2.setItemText(21, "38.6")
        self.comboBox_gain_2.setItemText(22, "40.2")
        self.comboBox_gain_2.setItemText(23, "42.1")
        self.comboBox_gain_2.setItemText(24, "43.4")
        self.comboBox_gain_2.setItemText(25, "43.9")
        self.comboBox_gain_2.setItemText(26, "44.5")
        self.comboBox_gain_2.setItemText(27, "48.0")
        self.comboBox_gain_2.setItemText(28, "49.6")

        self.label_gain_3.setText("RX3 Gain [dB]:")
        self.comboBox_gain_3.setItemText(0, "0")
        self.comboBox_gain_3.setItemText(1, "0.9")
        self.comboBox_gain_3.setItemText(2, "1.4")
        self.comboBox_gain_3.setItemText(3, "2.7")
        self.comboBox_gain_3.setItemText(4, "3.7")
        self.comboBox_gain_3.setItemText(5, "7.7")
        self.comboBox_gain_3.setItemText(6, "8.7")
        self.comboBox_gain_3.setItemText(7, "12.5")
        self.comboBox_gain_3.setItemText(8, "14.4")
        self.comboBox_gain_3.setItemText(9, "15.7")
        self.comboBox_gain_3.setItemText(10, "16.6")
        self.comboBox_gain_3.setItemText(11, "19.7")
        self.comboBox_gain_3.setItemText(12, "20.7")
        self.comboBox_gain_3.setItemText(13, "22.9")
        self.comboBox_gain_3.setItemText(14, "25.4")
        self.comboBox_gain_3.setItemText(15, "28.0")
        self.comboBox_gain_3.setItemText(16, "29.7")
        self.comboBox_gain_3.setItemText(17, "32.8")
        self.comboBox_gain_3.setItemText(18, "33.8")
        self.comboBox_gain_3.setItemText(19, "36.4")
        self.comboBox_gain_3.setItemText(20, "37.2")
        self.comboBox_gain_3.setItemText(21, "38.6")
        self.comboBox_gain_3.setItemText(22, "40.2")
        self.comboBox_gain_3.setItemText(23, "42.1")
        self.comboBox_gain_3.setItemText(24, "43.4")
        self.comboBox_gain_3.setItemText(25, "43.9")
        self.comboBox_gain_3.setItemText(26, "44.5")
        self.comboBox_gain_3.setItemText(27, "48.0")
        self.comboBox_gain_3.setItemText(28, "49.6")

        self.label_gain_4.setText("RX4 Gain [dB]:")
        self.comboBox_gain_4.setItemText(0, "0")
        self.comboBox_gain_4.setItemText(1, "0.9")
        self.comboBox_gain_4.setItemText(2, "1.4")
        self.comboBox_gain_4.setItemText(3, "2.7")
        self.comboBox_gain_4.setItemText(4, "3.7")
        self.comboBox_gain_4.setItemText(5, "7.7")
        self.comboBox_gain_4.setItemText(6, "8.7")
        self.comboBox_gain_4.setItemText(7, "12.5")
        self.comboBox_gain_4.setItemText(8, "14.4")
        self.comboBox_gain_4.setItemText(9, "15.7")
        self.comboBox_gain_4.setItemText(10, "16.6")
        self.comboBox_gain_4.setItemText(11, "19.7")
        self.comboBox_gain_4.setItemText(12, "20.7")
        self.comboBox_gain_4.setItemText(13, "22.9")
        self.comboBox_gain_4.setItemText(14, "25.4")
        self.comboBox_gain_4.setItemText(15, "28.0")
        self.comboBox_gain_4.setItemText(16, "29.7")
        self.comboBox_gain_4.setItemText(17, "32.8")
        self.comboBox_gain_4.setItemText(18, "33.8")
        self.comboBox_gain_4.setItemText(19, "36.4")
        self.comboBox_gain_4.setItemText(20, "37.2")
        self.comboBox_gain_4.setItemText(21, "38.6")
        self.comboBox_gain_4.setItemText(22, "40.2")
        self.comboBox_gain_4.setItemText(23, "42.1")
        self.comboBox_gain_4.setItemText(24, "43.4")
        self.comboBox_gain_4.setItemText(25, "43.9")
        self.comboBox_gain_4.setItemText(26, "44.5")
        self.comboBox_gain_4.setItemText(27, "48.0")
        self.comboBox_gain_4.setItemText(28, "49.6")

        self.pushButton_set_receiver_config.setText("Set")
        self.groupBox_8.setTitle("IQ preprocessing")
        self.label_19.setText("FIR tap size:")
        self.label_2.setText("Filter BW [kHz]: ")
        self.label.setText("DC compensation:")
        self.label_20.setText("Decimation:")
        self.spinBox_fir_tap_size.setToolTip(
            "<html><head/><body><p>Set to 0 to disable FIR filtering.</p></body></html>",
        )
        self.checkBox_en_spectrum.setText("Enable spectrum display")
        self.groupBox.setTitle("Syncronization")
        self.label_12.setText("Enable sync display:")
        self.label_32.setText("Noise source ON/OFF")
        self.spinBox_resync_time.setToolTip(
            "<html><head/><body><p>Set to 10 or higher to automatically resync samples every x seconds. Values below 10 disable timed resync.</p></body></html>",
        )
        self.label_resync_time.setText("Set Resync Time")
        self.pushButton_del_sync_history.setText("Delete history")
        self.pushButton_sync.setText("Sample sync")
        self.pushButton_iq_calib.setText("Calibrate IQ")
        self.groupBox_2.setTitle("Antenna configarion")
        self.label_21.setText("Arrangement:")
        # self.label_24.setText("Spacing [lambda]:")
        self.label_24.setText("Spacing [meters]:")
        self.comboBox_antenna_alignment.setToolTip(
            "<html><head/><body><p>ULA (Uniform Linear Array)<br/>UCA (Uniform Ciruclar Array)</p></body></html>",
        )
        self.comboBox_antenna_alignment.setItemText(0, "ULA")
        self.comboBox_antenna_alignment.setItemText(1, "UCA")
        self.pushButton_DOA_cal_90.setText("Calibrate 90 deg")
        self.pushButton_DOA_cal_90.setToolTip(
            "<html><head/><body><p>NOTE: Reserved for future use. Not fully implemented in this version.</p></body></html>",
        )

        self.groupBox_4.setTitle("DOA estimation")
        self.label_10.setText("Sample size 2^x:")
        self.spinBox_DOA_sample_size.setToolTip(
            "<html><head/><body><p>NOTE: Reserved for future use. Does nothing in this version.</p></body></html>",
        )
        self.spinBox_pr_sample_size.setToolTip(
            "<html><head/><body><p>NOTE: Reserved for future use. Does nothing in this version.</p></body></html>",
        )

        self.label_11.setText("Enable/Disable:")
        self.label_9.setText("MUSIC")
        self.label_8.setText("MEM")
        self.label_7.setText("Capon")
        self.label_6.setText("Bartlett")
        self.label_16.setText("FB average:")
        self.label_5.setText("Methods:")
        self.label_15.setText("Corr. matrix")
        self.checkBox_en_passive_radar.setText("Enable passive radar processing")
        self.groupBox_3.setTitle("Channel configuration")
        self.label_13.setText("Reference channel:")
        self.label_14.setText("Surveillance channel:")
        self.label_30.setText("Sample size 2^x:")
        self.groupBox_5.setTitle("Time domain clutter cancellation")
        self.label_23.setText("Enable/Disable:")
        self.label_25.setText("Method:")
        self.label_26.setText("Filter dimension:")
        self.comboBox_td_filter_method.setItemText(0, "Wiener - SSMI")
        self.groupBox_9.setTitle("Cross-Correlation Detector")
        self.label_27.setText("max Range:")
        self.label_28.setText("max Doppler:")
        self.label_29.setText("Windowing:")
        self.comboBox_cc_det_windowing.setItemText(0, "Rectangular")
        self.comboBox_cc_det_windowing.setItemText(1, "Hamming")
        self.label_31.setText("Dynamic range: ")

        self.groupBox_11.setTitle("Peak Hold")
        self.label_37.setText("Peak Hold: ")

        self.groupBox_10.setTitle("Automatic detection (CA-CFAR)")
        self.label_35.setToolTip(
            "<html><head/><body><p>Estimation window has a rectangular shape ( L x L cell), where L is the input data here</p></body></html>",
        )
        self.label_35.setText("Estimation window: ")
        self.label_34.setText("Threshold [dB]:")
        self.label_33.setText("Enable/Disable")
        self.label_36.setToolTip(
            "<html><head/><body><p>Guard window has a rectangular shape ( G x GL cell), where G is the input data here</p></body></html>",
        )
        self.label_36.setText("Guard window: ")

        self.groupBox_6.setTitle("Status ")
        self.label_power_level.setText("OK")
        self.label_17.setText("Powel level:")
        self.label_update_rate.setText("-ms")
        self.label_22.setText("Update rate:")
        self.pushButton_close.setText("Exit")
        self.pushButton_proc_control.setText("Start processing")
        self.pushButton_dumping_data.setText("Start dumping data")
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_spectrum), "Configuration and Spectrum",
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_symc), "Sync",
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_DOA), "DOA estimation",
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), "Passive radar",
        )

